spring:
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566

env:
  aws:
    sqs:
      test-queue-url: http://sqs.ap-northeast-1.localhost.localstack.cloud:4566/000000000000/test-queue.fifo
