name: ci_message_api

on:
  workflow_dispatch:
  push:
    branches:
      - feature-**
    path:
      - web-api

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web-api

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Preparation for test
        run: |
          java --version
          chmod +x ./gradlew

      - name: test
        run: ./gradlew test
