name: ci_message_api

on:
  workflow_dispatch:
  push:
    branches:
      - feature-**
      - develop
    paths:
      - message-api

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: message-api
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
      - name: Preparation for tests
        run: |
          java --version
          chmod +x ./gradlew
      - name: test
        env:
          SPRING_PROFILES_ACTIVE: ci
        run: ./gradlew test
